name: sqlite3_native_assets
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  sqlite3:
  native_assets_cli: ^0.11.0
  native_toolchain_c: ^0.8.0
  logging: ^1.3.0
  http: ^1.3.0
  archive: ^4.0.2
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  sqlite3:
    path: ../sqlite3/
